### ISSUE TITLE
AIS/TIS geolocation data? 

### ISSUE THREAD

**Issue by mjones01** [NEONScience/NEON-geolocation#1]
Is the statement in the README for the TIS/AIS data:  "Location data will be available through the geoNEON package and the NEON API in the near future; still pending." still true?  I'm being told by AQU scientists that the data is on the portal and when I look from the API URL I can see location data for at least some locations (e.g., http://data.neonscience.org/api/v0/locations/PRPO.AOS.groundwater.well.001)

**Comment by cklunch** [comment]
There are some AIS locations available in the API, but almost no TIS locations. The geoNEON package doesn't yet have a function that works well for any IS locations. I'll rephrase the readme to make it clearer. Thanks!
