### ISSUE TITLE
Can't install package in R 3.6.3

### ISSUE THREAD

**Issue by adjablonski** [NEONScience/NEON-geolocation#11]
Hi,

I'm trying to install geoNEON in R studio using the command: 
`devtools::install_github("NEONScience/NEON-geolocation/geoNEON")`

It looks like there might be some issues with the package code when installing. The output I'm getting is:

`* installing *source* package 'geoNEON' ...
** using staged installation
** R
Error in parse(outFile) : 
  C:/Users/Andrew/AppData/Local/Temp/Rtmpk5QEkY/R.INSTALL8a70d81335a/geoNEON/R/getLocTOS.R:583:74: unexpected ')'
582:     all.return <- all.return[order(all.return$rowid),]
583:     all.return <- all.return[,!names(all.return) %in% c('rowid','points'))
                                                                              ^
ERROR: unable to collate and parse R files for package 'geoNEON'
* removing 'C:/Users/Andrew/Documents/R/win-library/3.6/geoNEON'
Error: Failed to install 'geoNEON' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Andrew/AppData/Local/Temp/RtmpSq1bat/file7bb861dd7ad/geoNEON_1.0.0.tar.gz’ had non-zero exit status`

It's pointing to lines 582 and 583 of geoNEON/R/getLocTOS.

**Comment by cklunch** [comment]
@adjablonski Thanks for the heads up, and sorry for the error! Fixed now.

**Comment by adjablonski** [comment]
@cklunch Great! Thanks so much :)
