### ISSUE TITLE
Typo in getLocTOS.R

### ISSUE THREAD

**Issue by claraqin** [NEONScience/NEON-geolocation#12]
**Function**
geoNEON/R/getLocTOS.R
Lines 147 and 148: I believe `subplot.merg` should be replaced with `plot.merg`, and `subplot.loc` should be replaced with `plot.loc`.

**Describe the bug**
I receive the following error message:
```
Error in base::merge(data, subplot.merg, by = locCol, all.x = T) : 
  object 'subplot.merg' not found
```

**To Reproduce**
N/A

**Expected behavior**
N/A

**System (please complete the following information):**
 - OS: iOS
 - OS Version: 10.14
 - R Version: 3.6.0

**Comment by cklunch** [comment]
@claraqin Good catch, sorry about that! Should be fixed now.
