### ISSUE TITLE
Is it possible to get the spatial extent of the vegetation structure subplots?

### ISSUE THREAD

**Issue by hrodmn** [NEONScience/NEON-geolocation#17]
I am generating spatially-explicit predictions of forest structure (biomass, basal area, species composition, etc.) and I am very interested in using the NEON plot data to evaluate these predictions! I have played around with the locations endpoint and have successfully generated the spatial footprint of the vegetation structure base plots (40 x 40 meters) but I have not yet found any information about the spatial extent of the subplots.

How would you go about generating the footprint of the four subplots (e.g. subplots 21, 23, 39, 41) as shown in this figure from the vegetation structure users guide?

![image](https://user-images.githubusercontent.com/17726304/212772848-e57ba8e4-8ea5-477d-b0b3-340df61cf074.png)

Are the named subplots always oriented like this figure? i.e. 21 in southwest, 23 in southeast, 39 in northwest, 41 in northeast corner. Are the subplot descriptions with centroid/side length available via locations API?

Thanks for all of your hard work on this package and the NEON API!

**Comment by cklunch** [comment]
@hrodmn Thanks for getting in touch about this! We are currently working on an update to improve the way the subplot location data are provided via the API, but it's taking some time. But we can help you out in the meantime. Can you submit this question to the [NEON Contact Us form](https://www.neonscience.org/about/contact-us)? That will be the easiest way to get your inquiry to the people who can best answer it. Thanks!

**Comment by hrodmn** [comment]
Thanks @cklunch. That is exciting news about the subplot update. I will send my question to NEON support.
