### ISSUE TITLE
No geoNEON for R 3.6.1

### ISSUE THREAD

**Issue by mjones01** [NEONScience/NEON-geolocation#8]
**Function**
devtools::install_github("NEONScience/NEON-geolocation/geoNEON")
[Edit: correct function]
**Describe the bug**
Unable to install the package. When tried, we get the following message: 
Warning in install.packages: package 'geoNEON' is not available ( for R version 3.6.1). 

**To Reproduce**
This occurred on all computers in today's workshop that had R 3.6.1 installed.

**System (please complete the following information):**
 - OS: several
 - OS Version: several
 - R Version: 3.6.1

**Comment by cklunch** [comment]
@mjones01 Thanks for the alert, I'm running 3.6.1 on my machine, and I'm unable to replicate this. Do we have it happening on a machine that's coming back to HQ so I can troubleshoot?

**Comment by mjones01** [comment]
@cklunch No we had the issue on four computers on Friday AM but nobody else had updated to R 3.6.1 and with the issue, we didn't want to try mid-workshop.

**Comment by cklunch** [comment]
@mjones01 Got it, makes sense. Are we sure they weren't using install.packages()? Because if you try to run `install.packages('geoNEON')`, the error message you get is Warning in install.packages: package 'geoNEON' is not available ( for R version 3.6.1).
